[versions]
# Minecraft/Fabric related stuff
minecraft = "1.21.5"
fabricLoader = "0.16.13"
fabricKotlin = "1.13.2+kotlin.2.1.20"
loom = "1.10.1"

kotlin = "2.1.20"
compose-plugin = "1.8.0-beta02"

# TMP
modmenu = "14.0.0-rc.2"
fabric-api = "0.120.0+1.21.5"

[libraries]
# Minecraft/Fabric related stuff
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabricKotlin" }

# TMP
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

[plugins]
# Minecraft/Fabric related stuff
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }